// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_content_delivery_bucket": "qrcode-20190329114756--hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://qrcode-20190329114756--hostingbucket.s3-website-eu-west-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "eu-west-1:2e5fd447-a6a9-4470-8790-7594c8950abd",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_1b4NPumtl",
    "aws_user_pools_web_client_id": "760cc2jr4mfo40k7etgr1bvckp",
    "aws_user_files_s3_bucket": "qrcodebbae64624e2c4eaa95c85650b48ffb6c",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
